//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKRLP
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class faultDetail
    {
        
        private string majorField;
        
        private string minorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string major
        {
            get
            {
                return this.majorField;
            }
            set
            {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string minor
        {
            get
            {
                return this.minorField;
            }
            set
            {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public partial class PersonMaritalStatusStructure
    {
        
        private MaritalStatusType maritalStatusField;
        
        private VerificationLevelType verificationLevelField;
        
        private bool verificationLevelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MaritalStatusType MaritalStatus
        {
            get
            {
                return this.maritalStatusField;
            }
            set
            {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VerificationLevelType VerificationLevel
        {
            get
            {
                return this.verificationLevelField;
            }
            set
            {
                this.verificationLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerificationLevelSpecified
        {
            get
            {
                return this.verificationLevelFieldSpecified;
            }
            set
            {
                this.verificationLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/core")]
    public enum MaritalStatusType
    {
        
        /// <remarks/>
        s,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        d,
        
        /// <remarks/>
        w,
        
        /// <remarks/>
        n,
        
        /// <remarks/>
        p,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public enum VerificationLevelType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Level 0")]
        Level0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Level 1")]
        Level1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Level 2")]
        Level2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Level 3")]
        Level3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public partial class PersonDeathDateStructure
    {
        
        private System.DateTime personDeathDateField;
        
        private VerificationLevelType verificationLevelField;
        
        private bool verificationLevelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime PersonDeathDate
        {
            get
            {
                return this.personDeathDateField;
            }
            set
            {
                this.personDeathDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VerificationLevelType VerificationLevel
        {
            get
            {
                return this.verificationLevelField;
            }
            set
            {
                this.verificationLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerificationLevelSpecified
        {
            get
            {
                return this.verificationLevelFieldSpecified;
            }
            set
            {
                this.verificationLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public partial class PersonBirthDateStructure
    {
        
        private System.DateTime personBirthDateField;
        
        private VerificationLevelType verificationLevelField;
        
        private bool verificationLevelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime PersonBirthDate
        {
            get
            {
                return this.personBirthDateField;
            }
            set
            {
                this.personBirthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VerificationLevelType VerificationLevel
        {
            get
            {
                return this.verificationLevelField;
            }
            set
            {
                this.verificationLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerificationLevelSpecified
        {
            get
            {
                return this.verificationLevelFieldSpecified;
            }
            set
            {
                this.verificationLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderQueryResultStructure
    {
        
        private ProviderRecordStructure[] matchingProviderRecordsField;
        
        private string queryIdField;
        
        private string stakeholderIdField;
        
        private string schemaVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MatchingProviderRecords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ProviderRecordStructure[] MatchingProviderRecords
        {
            get
            {
                return this.matchingProviderRecordsField;
            }
            set
            {
                this.matchingProviderRecordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string QueryId
        {
            get
            {
                return this.queryIdField;
            }
            set
            {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string StakeholderId
        {
            get
            {
                return this.stakeholderIdField;
            }
            set
            {
                this.stakeholderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderRecordStructure
    {
        
        private string unitedKingdomProviderReferenceNumberField;
        
        private string providerNameField;
        
        private string accessibleProviderNameField;
        
        private string providerStatusField;
        
        private ProviderContactStructure[] providerContactField;
        
        private System.DateTime providerVerificationDateField;
        
        private bool providerVerificationDateFieldSpecified;
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private AssociationRecordStructure[] providerAssociationsField;
        
        private ProviderAliasesStructure[] providerAliasesField;
        
        private VerificationDetailsStructure[] verificationDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=0)]
        public string UnitedKingdomProviderReferenceNumber
        {
            get
            {
                return this.unitedKingdomProviderReferenceNumberField;
            }
            set
            {
                this.unitedKingdomProviderReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProviderName
        {
            get
            {
                return this.providerNameField;
            }
            set
            {
                this.providerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AccessibleProviderName
        {
            get
            {
                return this.accessibleProviderNameField;
            }
            set
            {
                this.accessibleProviderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ProviderStatus
        {
            get
            {
                return this.providerStatusField;
            }
            set
            {
                this.providerStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProviderContact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ProviderContactStructure[] ProviderContact
        {
            get
            {
                return this.providerContactField;
            }
            set
            {
                this.providerContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime ProviderVerificationDate
        {
            get
            {
                return this.providerVerificationDateField;
            }
            set
            {
                this.providerVerificationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProviderVerificationDateSpecified
        {
            get
            {
                return this.providerVerificationDateFieldSpecified;
            }
            set
            {
                this.providerVerificationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProviderAssociations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public AssociationRecordStructure[] ProviderAssociations
        {
            get
            {
                return this.providerAssociationsField;
            }
            set
            {
                this.providerAssociationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProviderAliases", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ProviderAliasesStructure[] ProviderAliases
        {
            get
            {
                return this.providerAliasesField;
            }
            set
            {
                this.providerAliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VerificationDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public VerificationDetailsStructure[] VerificationDetails
        {
            get
            {
                return this.verificationDetailsField;
            }
            set
            {
                this.verificationDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderContactStructure
    {
        
        private string contactTypeField;
        
        private AddressStructure contactAddressField;
        
        private PersonNameStructure contactPersonalDetailsField;
        
        private string contactRoleField;
        
        private string contactTelephone1Field;
        
        private string contactTelephone2Field;
        
        private string contactFaxField;
        
        private string contactWebsiteAddressField;
        
        private string contactEmailField;
        
        private System.DateTime lastUpdatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ContactType
        {
            get
            {
                return this.contactTypeField;
            }
            set
            {
                this.contactTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public AddressStructure ContactAddress
        {
            get
            {
                return this.contactAddressField;
            }
            set
            {
                this.contactAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PersonNameStructure ContactPersonalDetails
        {
            get
            {
                return this.contactPersonalDetailsField;
            }
            set
            {
                this.contactPersonalDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ContactRole
        {
            get
            {
                return this.contactRoleField;
            }
            set
            {
                this.contactRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ContactTelephone1
        {
            get
            {
                return this.contactTelephone1Field;
            }
            set
            {
                this.contactTelephone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ContactTelephone2
        {
            get
            {
                return this.contactTelephone2Field;
            }
            set
            {
                this.contactTelephone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ContactFax
        {
            get
            {
                return this.contactFaxField;
            }
            set
            {
                this.contactFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ContactWebsiteAddress
        {
            get
            {
                return this.contactWebsiteAddressField;
            }
            set
            {
                this.contactWebsiteAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ContactEmail
        {
            get
            {
                return this.contactEmailField;
            }
            set
            {
                this.contactEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.lastUpdatedField;
            }
            set
            {
                this.lastUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukrlp.gov.uk/commonlibrary")]
    public partial class AddressStructure
    {
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string address4Field;
        
        private string townField;
        
        private string countyField;
        
        private string postCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Address3
        {
            get
            {
                return this.address3Field;
            }
            set
            {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address4
        {
            get
            {
                return this.address4Field;
            }
            set
            {
                this.address4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Town
        {
            get
            {
                return this.townField;
            }
            set
            {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/PersonDescriptives")]
    public partial class PersonNameStructure
    {
        
        private string[] personNameTitleField;
        
        private string[] personGivenNameField;
        
        private string personFamilyNameField;
        
        private string[] personNameSuffixField;
        
        private string personRequestedNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonNameTitle", Order=0)]
        public string[] PersonNameTitle
        {
            get
            {
                return this.personNameTitleField;
            }
            set
            {
                this.personNameTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonGivenName", Order=1)]
        public string[] PersonGivenName
        {
            get
            {
                return this.personGivenNameField;
            }
            set
            {
                this.personGivenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PersonFamilyName
        {
            get
            {
                return this.personFamilyNameField;
            }
            set
            {
                this.personFamilyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonNameSuffix", Order=3)]
        public string[] PersonNameSuffix
        {
            get
            {
                return this.personNameSuffixField;
            }
            set
            {
                this.personNameSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PersonRequestedName
        {
            get
            {
                return this.personRequestedNameField;
            }
            set
            {
                this.personRequestedNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class AssociationRecordStructure
    {
        
        private string typeOfAssociationField;
        
        private string associationIdField;
        
        private string associationDescriptionField;
        
        private string associationStatusField;
        
        private System.DateTime associationCreatedDateField;
        
        private string associationMembershipStatusField;
        
        private System.DateTime associationMemberSinceDateField;
        
        private System.DateTime associationMembershipEndDateField;
        
        private bool associationMembershipEndDateFieldSpecified;
        
        private YesNoType leadProviderFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TypeOfAssociation
        {
            get
            {
                return this.typeOfAssociationField;
            }
            set
            {
                this.typeOfAssociationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=1)]
        public string AssociationId
        {
            get
            {
                return this.associationIdField;
            }
            set
            {
                this.associationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AssociationDescription
        {
            get
            {
                return this.associationDescriptionField;
            }
            set
            {
                this.associationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AssociationStatus
        {
            get
            {
                return this.associationStatusField;
            }
            set
            {
                this.associationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime AssociationCreatedDate
        {
            get
            {
                return this.associationCreatedDateField;
            }
            set
            {
                this.associationCreatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AssociationMembershipStatus
        {
            get
            {
                return this.associationMembershipStatusField;
            }
            set
            {
                this.associationMembershipStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime AssociationMemberSinceDate
        {
            get
            {
                return this.associationMemberSinceDateField;
            }
            set
            {
                this.associationMemberSinceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime AssociationMembershipEndDate
        {
            get
            {
                return this.associationMembershipEndDateField;
            }
            set
            {
                this.associationMembershipEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssociationMembershipEndDateSpecified
        {
            get
            {
                return this.associationMembershipEndDateFieldSpecified;
            }
            set
            {
                this.associationMembershipEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public YesNoType LeadProviderFlag
        {
            get
            {
                return this.leadProviderFlagField;
            }
            set
            {
                this.leadProviderFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/core")]
    public enum YesNoType
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderAliasesStructure
    {
        
        private string providerAliasField;
        
        private object lastUpdatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ProviderAlias
        {
            get
            {
                return this.providerAliasField;
            }
            set
            {
                this.providerAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object LastUpdated
        {
            get
            {
                return this.lastUpdatedField;
            }
            set
            {
                this.lastUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class VerificationDetailsStructure
    {
        
        private string verificationAuthorityField;
        
        private string verificationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VerificationAuthority
        {
            get
            {
                return this.verificationAuthorityField;
            }
            set
            {
                this.verificationAuthorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VerificationID
        {
            get
            {
                return this.verificationIDField;
            }
            set
            {
                this.verificationIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class authenticationDetails
    {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class SelectionCriteriaStructure
    {
        
        private string[] unitedKingdomProviderReferenceNumberListField;
        
        private string[] providerNameListField;
        
        private string[] postcodeListField;
        
        private string searchTermField;
        
        private string basePostcodeField;
        
        private int maxDistanceFromBasePostcodeField;
        
        private bool maxDistanceFromBasePostcodeFieldSpecified;
        
        private System.DateTime providerUpdatedSinceField;
        
        private bool providerUpdatedSinceFieldSpecified;
        
        private System.DateTime providerVerifiedAfterField;
        
        private bool providerVerifiedAfterFieldSpecified;
        
        private System.DateTime providerVerifiedBeforeField;
        
        private bool providerVerifiedBeforeFieldSpecified;
        
        private QueryCriteriaConditionType criteriaConditionField;
        
        private bool criteriaConditionFieldSpecified;
        
        private string stakeholderIdField;
        
        private YesNoType approvedProvidersOnlyField;
        
        private bool approvedProvidersOnlyFieldSpecified;
        
        private string providerStatusField;
        
        private VerificationDetailsStructure verificationDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UnitedKingdomProviderReferenceNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", IsNullable=false)]
        public string[] UnitedKingdomProviderReferenceNumberList
        {
            get
            {
                return this.unitedKingdomProviderReferenceNumberListField;
            }
            set
            {
                this.unitedKingdomProviderReferenceNumberListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ProviderName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ProviderNameList
        {
            get
            {
                return this.providerNameListField;
            }
            set
            {
                this.providerNameListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Postcode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] PostcodeList
        {
            get
            {
                return this.postcodeListField;
            }
            set
            {
                this.postcodeListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SearchTerm
        {
            get
            {
                return this.searchTermField;
            }
            set
            {
                this.searchTermField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BasePostcode
        {
            get
            {
                return this.basePostcodeField;
            }
            set
            {
                this.basePostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int MaxDistanceFromBasePostcode
        {
            get
            {
                return this.maxDistanceFromBasePostcodeField;
            }
            set
            {
                this.maxDistanceFromBasePostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxDistanceFromBasePostcodeSpecified
        {
            get
            {
                return this.maxDistanceFromBasePostcodeFieldSpecified;
            }
            set
            {
                this.maxDistanceFromBasePostcodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime ProviderUpdatedSince
        {
            get
            {
                return this.providerUpdatedSinceField;
            }
            set
            {
                this.providerUpdatedSinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProviderUpdatedSinceSpecified
        {
            get
            {
                return this.providerUpdatedSinceFieldSpecified;
            }
            set
            {
                this.providerUpdatedSinceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime ProviderVerifiedAfter
        {
            get
            {
                return this.providerVerifiedAfterField;
            }
            set
            {
                this.providerVerifiedAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProviderVerifiedAfterSpecified
        {
            get
            {
                return this.providerVerifiedAfterFieldSpecified;
            }
            set
            {
                this.providerVerifiedAfterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime ProviderVerifiedBefore
        {
            get
            {
                return this.providerVerifiedBeforeField;
            }
            set
            {
                this.providerVerifiedBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProviderVerifiedBeforeSpecified
        {
            get
            {
                return this.providerVerifiedBeforeFieldSpecified;
            }
            set
            {
                this.providerVerifiedBeforeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public QueryCriteriaConditionType CriteriaCondition
        {
            get
            {
                return this.criteriaConditionField;
            }
            set
            {
                this.criteriaConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CriteriaConditionSpecified
        {
            get
            {
                return this.criteriaConditionFieldSpecified;
            }
            set
            {
                this.criteriaConditionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string StakeholderId
        {
            get
            {
                return this.stakeholderIdField;
            }
            set
            {
                this.stakeholderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public YesNoType ApprovedProvidersOnly
        {
            get
            {
                return this.approvedProvidersOnlyField;
            }
            set
            {
                this.approvedProvidersOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApprovedProvidersOnlySpecified
        {
            get
            {
                return this.approvedProvidersOnlyFieldSpecified;
            }
            set
            {
                this.approvedProvidersOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ProviderStatus
        {
            get
            {
                return this.providerStatusField;
            }
            set
            {
                this.providerStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public VerificationDetailsStructure VerificationDetails
        {
            get
            {
                return this.verificationDetailsField;
            }
            set
            {
                this.verificationDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ukrlp.gov.uk/commonlibrary")]
    public enum QueryCriteriaConditionType
    {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderQueryStructure
    {
        
        private SelectionCriteriaStructure selectionCriteriaField;
        
        private string queryIdField;
        
        private string schemaVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SelectionCriteriaStructure SelectionCriteria
        {
            get
            {
                return this.selectionCriteriaField;
            }
            set
            {
                this.selectionCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string QueryId
        {
            get
            {
                return this.queryIdField;
            }
            set
            {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3", ConfigurationName="UKRLP.ProviderQueryPortType")]
    public interface ProviderQueryPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="retrieveAllProviders", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(UKRLP.faultDetail), Action="retrieveAllProviders", Name="faultDetail")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PersonMaritalStatusStructure))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PersonDeathDateStructure))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PersonBirthDateStructure))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderQueryResultStructure))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(authenticationDetails))]
        System.Threading.Tasks.Task<UKRLP.response> retrieveAllProvidersAsync(UKRLP.ProviderQueryParam request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ukrlp.co.uk.server.ws.v3")]
    public partial class ProviderQueryResponse
    {
        
        private ProviderRecordStructure[] matchingProviderRecordsField;
        
        private string queryIdField;
        
        private string stakeholderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MatchingProviderRecords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ProviderRecordStructure[] MatchingProviderRecords
        {
            get
            {
                return this.matchingProviderRecordsField;
            }
            set
            {
                this.matchingProviderRecordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string QueryId
        {
            get
            {
                return this.queryIdField;
            }
            set
            {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string StakeholderId
        {
            get
            {
                return this.stakeholderIdField;
            }
            set
            {
                this.stakeholderIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProviderQueryParam
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3", Order=0)]
        public UKRLP.ProviderQueryStructure ProviderQueryRequest;
        
        public ProviderQueryParam()
        {
        }
        
        public ProviderQueryParam(UKRLP.ProviderQueryStructure ProviderQueryRequest)
        {
            this.ProviderQueryRequest = ProviderQueryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ukrlp.co.uk.server.ws.v3", Order=0)]
        public UKRLP.ProviderQueryResponse ProviderQueryResponse;
        
        public response()
        {
        }
        
        public response(UKRLP.ProviderQueryResponse ProviderQueryResponse)
        {
            this.ProviderQueryResponse = ProviderQueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ProviderQueryPortTypeChannel : UKRLP.ProviderQueryPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ProviderQueryPortTypeClient : System.ServiceModel.ClientBase<UKRLP.ProviderQueryPortType>, UKRLP.ProviderQueryPortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProviderQueryPortTypeClient() : 
                base(ProviderQueryPortTypeClient.GetDefaultBinding(), ProviderQueryPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProviderQueryPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderQueryPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ProviderQueryPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ProviderQueryPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderQueryPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProviderQueryPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderQueryPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProviderQueryPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProviderQueryPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<UKRLP.response> retrieveAllProvidersAsync(UKRLP.ProviderQueryParam request)
        {
            return base.Channel.retrieveAllProvidersAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProviderQueryPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProviderQueryPort))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.ukrlp.co.uk/UkrlpProviderQueryWS5/ProviderQueryServiceV5");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProviderQueryPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ProviderQueryPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProviderQueryPortTypeClient.GetEndpointAddress(EndpointConfiguration.ProviderQueryPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ProviderQueryPort,
        }
    }
}
