
CREATE TABLE [dbo].[WhitelistedProviders](
	[UKPRN] [int] NOT NULL,
 CONSTRAINT [PK_WhitelistedProviders] PRIMARY KEY CLUSTERED 
(
	[UKPRN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

