DROP TABLE IF EXISTS LookupPageTitles
GO

CREATE TABLE LookupPageTitles
(
	[SequenceNumber] INT NOT NULL,
	[SectionNumber] INT NOT NULL,
	[PageId] NVARCHAR(50) NOT NULL,
	[Title] NVARCHAR(100)
)
GO

INSERT INTO LookupPageTitles ([SequenceNumber],[SectionNumber],[PageId],[Title]) VALUES
(0, 1, '1', 'Preamble'),
(0, 1, '2', 'Provider route'),
(0, 1, '3', 'Conditions of acceptance'),

(1, 1, '10', 'Your organisation'),
(1, 1, '11', 'Your organisation'),
(1, 1, '12', 'Your organisation'),

(1, 2, '20', 'Does your organisation have an ultimate parent company in the UK?'),
(1, 2, '21', 'Enter your organisation''s ultimate parent company details'),
(1, 2, '30', 'What is your organisation''s Information Commissioner''s Office (ICO) registration number?'),
(1, 2, '40', 'Does your organisation have a website?'),

(1, 3, '70', 'Confirm who''s in control - Companies House'),
(1, 3, '80', 'Confirm who''s in control - Trustees'),
(1, 3, '90', 'Confirm who''s in control - Add Trustees'),
(1, 3, '100', 'Tell us your organisation''s type'),
(1, 3, '101', 'What is your organisation''s partner?'),
(1, 3, '110', 'Enter the individual''s details'),
(1, 3, '111', 'Enter the organisation''s details'),
(1, 3, '120', 'What is {{UKRLPLegalName}}''s date of birth?'),
(1, 3, '130', 'Confirm who''s in control - Add People In Control'),

(1, 4, '140', 'What is your organisation?'),
(1, 4, '150', 'What is your organisation?'),
(1, 4, '160', 'What type of educational institute is your organisation?'),
(1, 4, '170', 'What type of public body is your organisation?'),
(1, 4, '180', 'What type of school is your organisation?'),
(1, 4, '200', 'Is your organisation registered and receiving funding from ESFA?'),
(1, 4, '210', 'Is your organisation receiving funding from ESFA?'),
(1, 4, '220', 'Is your organisation monitored and supported by the Office of Students?'),
(1, 4, '230', 'How would you describe your organisation?'),
(1, 4, '50', 'How long has your organisation been actively trading?'),
(1, 4, '60', 'How long has your organisation been actively trading?'),
(1, 4, '10001', 'Your organisation is not eligible to apply to join RoATP'),
(1, 4, '10002', 'Your organisation is not eligible to apply to join RoATP'),
(1, 4, '10003', 'Your organisation is not eligible to apply to join RoATP'),

(1, 5, '235', 'Is your organisation funded by the Office for Students?'),
(1, 5, '240', 'Does your organisation offer initial teacher training?'),
(1, 5, '250', 'Is the postgraduate teaching apprenticeship the only apprenticeship your organisation intends to deliver?'),
(1, 5, '260', 'Has your organisation had a full Ofsted inspection in further education and skills?'),
(1, 5, '270', 'Did your organisation get a grade for apprenticeships in this full Ofsted inspection?'),
(1, 5, '280', 'What grade did your organisation get for overall effectiveness in this full Ofsted inspection?'),
(1, 5, '290', 'Has your organisation had a monitoring visit for apprenticeships in further education and skills?'),
(1, 5, '292', 'Has your organisation had 2 consecutive monitoring visits with the grade ''insufficient progress''?'),
(1, 5, '294', 'Was the most recent monitoring visit within the last 18 months?'),
(1, 5, '300', 'What grade did your organisation get for apprenticeships in this full Ofsted inspection?'),
(1, 5, '301', 'What grade did your organisation get for apprenticeships in this full Ofsted inspection?'),
(1, 5, '310', 'Did your organisation get this grade within the last 3 years?'),
(1, 5, '311', 'Did your organisation get this grade within the last 3 years?'),
(1, 5, '320', 'Has your organisation maintained funding from an education agency since its full Ofsted inspection?'),
(1, 5, '330', 'Has your organisation had a short Ofsted inspection within the last 3 years?'),
(1, 5, '340', 'Has your organisation maintained the grade it got in its full Ofsted inspection in its short Ofsted inspection?'),
(1, 5, '350', 'Has your organisation delivered apprenticeship training as a subcontractor in the last 12 months?'),
(1, 5, '360', 'Upload a copy of a legally binding contract between your organisation and a main or employer provider'),
(1, 5, '10004', 'Your organisation is not eligible to apply to join RoATP'),
(1, 5, '10010', 'Your organisation is not eligible to apply to join RoATP'),

(2, 1, '2000', 'Financial health assessment'),
(2, 1, '2010', 'Financial health assessment'),

(2, 2, '2100', 'Was your organisation''s total annual turnover over £75 million for the latest reported financial year?'),
(2, 2, '2110', 'Does your organisation expect its funding from ESFA to be less than 5% of its total annual turnover?'),
(2, 2, '2120', 'Financial evidence'),
(2, 2, '2130', 'Financial evidence'),
(2, 2, '2140', 'Financial evidence'),
(2, 2, '2150', 'Has your organisation produced its latest full financial statements covering a minimum of 12 months?'),
(2, 2, '2160', 'Upload your organisation''s latest full financial statements covering the last 12 months'),
(2, 2, '2170', 'Has your organisation produced financial statements covering any period within the last 12 months?'),
(2, 2, '2180', 'What you need to upload'),
(2, 2, '2190', 'Upload your organisation''s financial statements covering any period within the last 12 months'),
(2, 2, '2195', 'What you need to upload'),
(2, 2, '2200', 'Upload your organisation''s management accounts covering the remaining period to date'),
(2, 2, '2210', 'Has your organisation produced full management accounts covering the last 12 months?'),
(2, 2, '2220', 'What you need to upload'),
(2, 2, '2225', 'Upload your organisation''s full management accounts for the last 12 months'),
(2, 2, '2230', 'What you need to upload'),
(2, 2, '2240', 'Upload your organisation''s management accounts covering at least 3 months within the last 12 months'),
(2, 2, '2250', 'Upload your organisation''s financial projections covering the remaining period'),
(2, 2, '2260', 'Who prepared the answers and uploads in this section?'),
(2, 2, '2270', 'What''s the accounting reference date for the financial information you are submitting?'),
(2, 2, '2280', 'How many months does the accounting period cover for the financial information you are submitting?'),

(2, 3, '2500', 'Does your UK ultimate parent company have consolidated financial statements?'),
(2, 3, '2510', 'Upload your UK ultimate parent company''s consolidated financial statements'),
(2, 3, '2520', 'Does your UK ultimate parent company have other active subsidiary companies?'),
(2, 3, '2530', 'Upload a financial statement for all your UK ultimate parent company''s active subsidiary companies'),
(2, 3, '2540', 'Upload your UK ultimate parent company''s full financial statements covering the last 12 months'),

(3, 1, '3000', 'Criminal and compliance checks on your organisation'),

(3, 2, '3100', 'Checks on your organisation'),
(3, 2, '3110', 'Checks on your organisation'),
(3, 2, '3120', 'Checks on your organisation'),
(3, 2, '3130', 'Checks on your organisation'),
(3, 2, '3135', 'Checks on your organisation'),
(3, 2, '3140', 'Checks on your organisation'),
(3, 2, '3150', 'Checks on your organisation'),
(3, 2, '3160', 'Checks on your organisation'),
(3, 2, '3170', 'Checks on your organisation'),
(3, 2, '3180', 'Checks on your organisation'),
(3, 2, '3190', 'Checks on your organisation'),
(3, 2, '3199', 'Checks on your organisation'),

(3, 3, '3200', 'Criminal and compliance checks on who''s in control of your organisation'),

(3, 4, '3300', 'Checks on who''s in control of your organisation'),
(3, 4, '3301', 'Checks on who''s in control of your organisation'),
(3, 4, '3310', 'Checks on who''s in control of your organisation'),
(3, 4, '3311', 'Checks on who''s in control of your organisation'),
(3, 4, '3320', 'Checks on who''s in control of your organisation'),
(3, 4, '3321', 'Checks on who''s in control of your organisation'),
(3, 4, '3330', 'Checks on who''s in control of your organisation'),
(3, 4, '3331', 'Checks on who''s in control of your organisation'),
(3, 4, '3340', 'Checks on who''s in control of your organisation'),
(3, 4, '3341', 'Checks on who''s in control of your organisation'),
(3, 4, '3350', 'Checks on who''s in control of your organisation'),
(3, 4, '3351', 'Checks on who''s in control of your organisation'),
(3, 4, '3360', 'Checks on who''s in control of your organisation'),
(3, 4, '3361', 'Checks on who''s in control of your organisation'),
(3, 4, '3370', 'Checks on who''s in control of your organisation'),
(3, 4, '3371', 'Checks on who''s in control of your organisation'),
(3, 4, '3380', 'Checks on who''s in control of your organisation'),
(3, 4, '3381', 'Checks on who''s in control of your organisation'),
(3, 4, '3390', 'Checks on who''s in control of your organisation'),
(3, 4, '3391', 'Checks on who''s in control of your organisation'),
(3, 4, '3395', 'Checks on who''s in control of your organisation'),
(3, 4, '3396', 'Checks on who''s in control of your organisation'),

(4, 1, '4000', 'Protecting your apprentices'),
(4, 1, '4001', 'Protecting your apprentices'),
(4, 1, '4002', 'Protecting your apprentices'),

(4, 2, '4010', 'Continuity plan for apprenticeship training'),

(4, 3, '4020', 'Equality and diversity policy'),

(4, 4, '4030', 'Safeguarding and Prevent duty policy'),
(4, 4, '4035', 'Tell us who has overall responsibility for safeguarding in your organisation'),
(4, 4, '4037', 'Does your organisation''s safeguarding policy include its responsibilities towards the Prevent duty?'),
(4, 4, '4038', 'Upload your organisation''s Prevent duty policy'),

(4, 5, '4040', 'Health and safety policy'),
(4, 5, '4045', 'Tell us who has overall responsibility for health and safety in your organisation'),

(4, 6, '4050', 'Acting as a subcontractor'),

(5, 1, '5000', 'Readiness to engage'),
(5, 1, '5010', 'Readiness to engage'),
(5, 1, '5020', 'Readiness to engage'),

(5, 2, '5100', 'Engaging with employers'),
(5, 2, '5110', 'Engaging with employers'),
(5, 2, '5120', 'Tell us who''s responsible for managing relationships with employers'),
(5, 2, '5130', 'Engaging with employers'),

(5, 3, '5200', 'Complaints policy'),
(5, 3, '5210', 'Complaints policy'),

(5, 4, '5300', 'Contract for services template'),

(5, 5, '5400', 'Commitment statement template'),

(5, 6, '5500', 'Prior learning of apprentices'),
(5, 6, '5510', 'Prior learning of apprentices'),

(5, 7, '5550', 'English and maths assessments'),
(5, 7, '5560', 'English and maths assessments'),

(5, 7, '5570', 'English and maths assessments holding page'),

(5, 8, '5600', 'Working with subcontractors'),
(5, 8, '5610', 'Working with subcontractors'),

(6, 1, '6000', 'Planning apprenticeship training'),
(6, 1, '6001', 'Planning apprenticeship training'),
(6, 1, '6002', 'Planning apprenticeship training'),

(6, 2, '6201', 'Type of apprenticeship training'),
(6, 2, '6202', 'Type of apprenticeship training'),
(6, 2, '6203', 'Type of apprenticeship training'),
(6, 2, '6230', 'Application standards'),
(6, 2, '6250', 'Apprenticeship frameworks'),
(6, 2, '6252', 'Organisation transition'),
(6, 2, '6253', 'Organisation transition'),
(6, 2, '6254', 'Why will your organisation only deliver apprenticeship frameworks?'),
(6, 2, '6260', 'Application frameworks'),
(6, 2, '6262', 'Organisation transition'),
(6, 2, '6264', 'Why will your organisation only deliver apprenticeship frameworks?'),
(6, 2, '6270', 'How will your organisation engage with end-point assessment organisations (EPAOs)?'),
(6, 2, '6280', 'How will your organisation plan to engage and work with awarding bodies?'),

(6, 3, '6300', 'How will your organisation train its apprentices?'),

(6, 4, '6400', 'How will your organisation ensure apprentices are supported during their apprenticeship training?'),
(6, 4, '6405', 'How will your organisation ensure apprentices are supported during their apprenticeship training?'),
(6, 4, '6410', 'How will your organisation support its apprentices?'),
(6, 4, '6420', 'What other ways will your organisation use to support its apprentices?'),

(6, 5, '6500', 'Forecasting starts'),
(6, 5, '6510', 'Ready to deliver against starts'),
(6, 5, '6520', 'Recruit staff to deliver'),
(6, 5, '6530', 'Staff Apprentice Ratio'),
(6, 5, '6540', 'Proposed staff to learner support'),

(6, 6, '6600', 'What teaching methods will your organisation use to deliver 20% off the job training?'),
(6, 6, '6610', 'How will your organisation ensure 20% off the job training is relevant to the specific apprenticeship being delivered?'),

(6, 7, '6700', 'Where will your apprentices be trained?'),

(7, 1, '7000', 'Delivering apprenticeship training'),
(7, 1, '7001', 'Delivering apprenticeship training'),
(7, 1, '7002', 'Delivering apprenticeship training'),

(7, 2, '7100', 'Tell us who has overall accountability for apprenticeships in your organisation'),

(7, 3, '7200', 'Confirm management hierarchy'),

(7, 4, '7300', 'Upload your management hierarchy''s expectations for quality and high standards in apprenticeship training'),
(7, 4, '7305', 'Tell us how these expectations for quality and high standards in apprenticeship training are monitored and evaluated'),
(7, 4, '7310', 'Tell us who''s responsible for maintaining these expectations for quality and high standards in apprenticeship training'),
(7, 4, '7320', 'How are these expectations for quality and high standards in apprenticeship training communicated to employees'),

(7, 5, '7500', 'Developing and delivering training'),
(7, 5, '7510', 'Developing and delivering training'),
(7, 5, '7520', 'Developing and delivering training'),
(7, 5, '7530', 'Developing and delivering training'),
(7, 5, '7540', 'Tell us who''s the overall manager for this team'),
(7, 5, '7560', 'Developing and delivering training'),
(7, 5, '7570', 'How has the team worked with other organisations to develop and deliver training?'),
(7, 5, '7590', 'Tell us who''s the overall manager for this team'),
(7, 5, '7591', 'How has the team worked with other organisations and employers to develop and deliver training?'),
(7, 5, '7592', 'How has the team worked with employers to develop and deliver training?'),
(7, 5, '7593', 'How has this person worked with other organisations to develop and deliver training?'),
(7, 5, '7594', 'How has this person worked with other organisations and employers to develop and deliver training?'),
(7, 5, '7595', 'How has this person worked with employers to develop and deliver training?'),

(7, 6, '7600', 'Your organisation''s sectors'),
(7, 6, '7610AA', 'Agriculture, environmental and animal care'),
(7, 6, '7610A', 'Agriculture, environmental and animal care'),
(7, 6, '7610B', 'Agriculture, environmental and animal care'),
(7, 6, '7610', 'Agriculture, environmental and animal care'),
(7, 6, '7611', '{{DATAgricultureFirstName}} {{DATAgricultureLastName}}''s experience in the ''Agriculture, environmental and animal care'' sector'),
(7, 6, '7612', '{{DATAgricultureFirstName}} {{DATAgricultureLastName}}''s experience in the ''Agriculture, environmental and animal care'' sector'),
(7, 6, '7613', '{{DATAgricultureFirstName}} {{DATAgricultureLastName}}''s experience in the ''Agriculture, environmental and animal care'' sector'),
(7, 6, '7615AA', 'Business and administration'),
(7, 6, '7615A', 'Business and administration'),
(7, 6, '7615B', 'Business and administration'),
(7, 6, '7615', 'Business and administration'),
(7, 6, '7616', '{{DATBusinessFirstName}} {{DATBusinessLastName}}''s experience in the ''Business and administration'' sector'),
(7, 6, '7617', '{{DATBusinessFirstName}} {{DATBusinessLastName}}''s experience in the ''Business and administration'' sector'),
(7, 6, '7618', '{{DATBusinessFirstName}} {{DATBusinessLastName}}''s experience in the ''Business and administration'' sector'),
(7, 6, '7620AA', 'Care services'),
(7, 6, '7620A', 'Care services'),
(7, 6, '7620B', 'Care services'),
(7, 6, '7620', 'Care services'),
(7, 6, '7621', '{{DATCareServicesFirstName}} {{DATCareServicesLastName}}''s experience in the ''Care services'' sector'),
(7, 6, '7622', '{{DATCareServicesFirstName}} {{DATCareServicesLastName}}''s experience in the ''Care services'' sector'),
(7, 6, '7623', '{{DATCareServicesFirstName}} {{DATCareServicesLastName}}''s experience in the ''Care services'' sector'),
(7, 6, '7625AA', 'Catering and hospitality'),
(7, 6, '7625A', 'Catering and hospitality'),
(7, 6, '7625B', 'Catering and hospitality'),
(7, 6, '7625', 'Catering and hospitality'),
(7, 6, '7626', '{{DATCateringFirstName}} {{DATCateringLastName}}''s experience in the ''Catering and hospitality'' sector'),
(7, 6, '7627', '{{DATCateringFirstName}} {{DATCateringLastName}}''s experience in the ''Catering and hospitality'' sector'),
(7, 6, '7628', '{{DATCateringFirstName}} {{DATCateringLastName}}''s experience in the ''Catering and hospitality'' sector'),
(7, 6, '7630AA', 'Construction'),
(7, 6, '7630A', 'Construction'),
(7, 6, '7630B', 'Construction'),
(7, 6, '7630', 'Construction'),
(7, 6, '7631', '{{DATConstructionFirstName}} {{DATConstructionLastName}}''s experience in the ''Construction'' sector'),
(7, 6, '7632', '{{DATConstructionFirstName}} {{DATConstructionLastName}}''s experience in the ''Construction'' sector'),
(7, 6, '7633', '{{DATConstructionFirstName}} {{DATConstructionLastName}}''s experience in the ''Construction'' sector'),
(7, 6, '7635AA', 'Creative and design'),
(7, 6, '7635A', 'Creative and design'),
(7, 6, '7635B', 'Creative and design'),
(7, 6, '7635', 'Creative and design'),
(7, 6, '7636', '{{DATCreativeFirstName}} {{DATCreativeLastName}}''s experience in the ''Creative and design'' sector'),
(7, 6, '7637', '{{DATCreativeFirstName}} {{DATCreativeLastName}}''s experience in the ''Creative and design'' sector'),
(7, 6, '7638', '{{DATCreativeFirstName}} {{DATCreativeLastName}}''s experience in the ''Creative and design'' sector'),
(7, 6, '7640AA', 'Digital'),
(7, 6, '7640A', 'Digital'),
(7, 6, '7640B', 'Digital'),
(7, 6, '7640', 'Digital'),
(7, 6, '7641', '{{DATDigitalFirstName}} {{DATDigitalLastName}}''s experience in the ''Digital'' sector'),
(7, 6, '7642', '{{DATDigitalFirstName}} {{DATDigitalLastName}}''s experience in the ''Digital'' sector'),
(7, 6, '7643', '{{DATDigitalFirstName}} {{DATDigitalLastName}}''s experience in the ''Digital'' sector'),
(7, 6, '7645AA', 'Education and childcare'),
(7, 6, '7645A', 'Education and childcare'),
(7, 6, '7645B', 'Education and childcare'),
(7, 6, '7645', 'Education and childcare'),
(7, 6, '7646', '{{DATEducationFirstName}} {{DATEducationLastName}}''s experience in the ''Education and childcare'' sector'),
(7, 6, '7647', '{{DATEducationFirstName}} {{DATEducationLastName}}''s experience in the ''Education and childcare'' sector'),
(7, 6, '7648', '{{DATEducationFirstName}} {{DATEducationLastName}}''s experience in the ''Education and childcare'' sector'),
(7, 6, '7650AA', 'Engineering and manufacturing'),
(7, 6, '7650A', 'Engineering and manufacturing'),
(7, 6, '7650B', 'Engineering and manufacturing'),
(7, 6, '7650', 'Engineering and manufacturing'),
(7, 6, '7651', '{{DATEngineeringFirstName}} {{DATEngineeringLastName}}''s experience in the ''Engineering and manufacturing'' sector'),
(7, 6, '7652', '{{DATEngineeringFirstName}} {{DATEngineeringLastName}}''s experience in the ''Engineering and manufacturing'' sector'),
(7, 6, '7653', '{{DATEngineeringFirstName}} {{DATEngineeringLastName}}''s experience in the ''Engineering and manufacturing'' sector'),
(7, 6, '7655AA', 'Hair and Beauty'),
(7, 6, '7655A', 'Hair and Beauty'),
(7, 6, '7655', 'Hair and Beauty'),
(7, 6, '7655B', 'Hair and Beauty'),
(7, 6, '7656', '{{DATHairAndBeautyFirstName}} {{DATHairAndBeautyLastName}}''s experience in the ''Hair and Beauty'' sector'),
(7, 6, '7657', '{{DATHairAndBeautyFirstName}} {{DATHairAndBeautyLastName}}''s experience in the ''Hair and Beauty'' sector'),
(7, 6, '7658', '{{DATHairAndBeautyFirstName}} {{DATHairAndBeautyLastName}}''s experience in the ''Hair and Beauty'' sector'),
(7, 6, '7660AA', 'Health and science'),
(7, 6, '7660A', 'Health and science'),
(7, 6, '7660B', 'Health and science'),
(7, 6, '7660', 'Health and science'),
(7, 6, '7661', '{{DATHealthAndScienceFirstName}} {{DATHealthAndScienceLastName}}''s experience in the ''Health and science'' sector'),
(7, 6, '7662', '{{DATHealthAndScienceFirstName}} {{DATHealthAndScienceLastName}}''s experience in the ''Health and science'' sector'),
(7, 6, '7663', '{{DATHealthAndScienceFirstName}} {{DATHealthAndScienceLastName}}''s experience in the ''Health and science'' sector'),
(7, 6, '7665AA', 'Legal, finance and accounting'),
(7, 6, '7665A', 'Legal, finance and accounting'),
(7, 6, '7665B', 'Legal, finance and accounting'),
(7, 6, '7665', 'Legal, finance and accounting'),
(7, 6, '7666', '{{DATLegalFirstName}} {{DATLegalLastName}}''s experience in the ''Legal, finance and accounting'' sector'),
(7, 6, '7667', '{{DATLegalFirstName}} {{DATLegalLastName}}''s experience in the ''Legal, finance and accounting'' sector'),
(7, 6, '7668', '{{DATLegalFirstName}} {{DATLegalLastName}}''s experience in the ''Legal, finance and accounting'' sector'),
(7, 6, '7670AA', 'Protective services'),
(7, 6, '7670A', 'Protective services'),
(7, 6, '7670B', 'Protective services'),
(7, 6, '7670', 'Protective services'),
(7, 6, '7671', '{{DATProtectiveServicesFirstName}} {{DATProtectiveServicesLastName}}''s experience in the ''Protective services'' sector'),
(7, 6, '7672', '{{DATProtectiveServicesFirstName}} {{DATProtectiveServicesLastName}}''s experience in the ''Protective services'' sector'),
(7, 6, '7673', '{{DATProtectiveServicesFirstName}} {{DATProtectiveServicesLastName}}''s experience in the ''Protective services'' sector'),
(7, 6, '7675AA', 'Sales, marketing and procurement'),
(7, 6, '7675A', 'Sales, marketing and procurement'),
(7, 6, '7675B', 'Sales, marketing and procurement'),
(7, 6, '7675', 'Sales, marketing and procurement'),
(7, 6, '7676', '{{DATSalesFirstName}} {{DATSalesLastName}}''s experience in the ''Sales, marketing and procurement'' sector'),
(7, 6, '7677', '{{DATSalesFirstName}} {{DATSalesLastName}}''s experience in the ''Sales, marketing and procurement'' sector'),
(7, 6, '7678', '{{DATSalesFirstName}} {{DATSalesLastName}}''s experience in the ''Sales, marketing and procurement'' sector'),
(7, 6, '7680AA', 'Transport and logistics'),
(7, 6, '7680A', 'Transport and logistics'),
(7, 6, '7680B', 'Transport and logistics'),
(7, 6, '7680', 'Transport and logistics'),
(7, 6, '7681', '{{DATTransportFirstName}} {{DATTransportLastName}}''s experience in the ''Transport and logistics'' sector'),
(7, 6, '7682', '{{DATTransportFirstName}} {{DATTransportLastName}}''s experience in the ''Transport and logistics'' sector'),
(7, 6, '7683', '{{DATTransportFirstName}} {{DATTransportLastName}}''s experience in the ''Transport and logistics'' sector'),

(7, 7, '7700', 'Upload your organisation''s contract for services template with employers'),
(7, 7, '7710', 'Give an example of how your organisation used this policy to improve employee sector expertise'),
(7, 7, '7720', 'Give an example of how your organisation used this policy to maintain employee teaching and training knowledge'),

(8, 1, '8000', 'Evaluating apprenticeship training'),
(8, 1, '8010', 'Evaluating apprenticeship training'),

(8, 2, '8100', 'Process for evaluating the quality of training delivered'),
(8, 2, '8110', 'Process for evaluating the quality of training delivered'),

(8, 3, '8200', 'Process of evaluating the quality of apprenticeship training'),
(8, 3, '8210', 'Process of evaluating the quality of apprenticeship training'),
(8, 3, '8220', 'Process of evaluating the quality of apprenticeship training'),
(8, 3, '8230', 'Process of evaluating the quality of apprenticeship training'),

(8, 4, '8300', 'Systems and processes to collect apprenticeship data'),
(8, 4, '8310', 'Systems and processes to collect apprenticeship data'),
(8, 4, '8320', 'Who is the individual accountable for submitting ILR data for your organisation?'),

(9, 1, '9000', 'Do you have permission from everyone named in this application to use their details?'),
(9, 1, '9010', 'Have you checked with everyone named in this application that the details provided for them are accurate?'),
(9, 1, '9020', 'Do you have permission from your organisation to submit this application?'),
(9, 1, '10005', 'Before you submit your application'),

(9, 2, '9100', 'Quality statement'),
(9, 2, '100055', 'Before you submit your application'),

(9, 3, '9200', 'Do you understand that your organisation will not join the RoATP until it completes all post application tasks?'),
(9, 3, '10006', 'Before you submit your application');