DROP TABLE IF EXISTS LookupPageTitles
GO

CREATE TABLE LookupPageTitles
(
	[SequenceNumber] INT NOT NULL,
	[SectionNumber] INT NOT NULL,
	[PageId] NVARCHAR(50) NOT NULL,
	[Title] NVARCHAR(255)
)
GO

INSERT INTO LookupPageTitles ([SequenceNumber],[SectionNumber],[PageId],[Title]) VALUES
(0, 1, '1', 'Preamble'),
(0, 1, '2', 'Provider route'),
(0, 1, '3', 'Conditions of acceptance'),

(1, 1, '10', 'Your organisation'),
(1, 1, '11', 'Your organisation'),
(1, 1, '12', 'Your organisation'),

(1, 2, '20', 'Ultimate parent company in the UK'),
(1, 2, '21', 'Ultimate parent company details'),
(1, 2, '30', 'Information Commissioner''s Office (ICO) registration number'),
(1, 2, '40', 'Organisation website'),

(1, 3, '70', 'Confirm who''s in control - Companies House'),
(1, 3, '80', 'Confirm who''s in control - Trustees'),
(1, 3, '86', 'Confirm who''s in control - Trustees date of birth'),
(1, 3, '90', 'Confirm who''s in control - Add Trustees'),
(1, 3, '100', 'Sole trader or Partnership'),
(1, 3, '101', 'Partnership type'),
(1, 3, '110', 'Individual''s details'),
(1, 3, '111', 'Organisation''s details'),
(1, 3, '120', 'Date of birth'),
(1, 3, '130', 'Confirm who''s in control - Manual Entry'),

(1, 4, '140', 'Describe your organisation'),
(1, 4, '150', 'Describe your organisation'),
(1, 4, '160', 'Education Institute type'),
(1, 4, '170', 'Public Body type'),
(1, 4, '180', 'School type'),
(1, 4, '200', 'Registered with ESFA'),
(1, 4, '210', 'Funded by ESFA'),
(1, 4, '220', 'Monitored by Office of Students'),
(1, 4, '230', 'Organisation description'),
(1, 4, '50', 'Actively trading'),
(1, 4, '60', 'Actively trading'),
(1, 4, '10001', 'Shutter Page - Actively trading for at least 12 months'),
(1, 4, '10002', 'Shutter Page - Actively trading for at least 12 months'),
(1, 4, '10003', 'Shutter Page - Actively trading for at least 3 months'),

(1, 5, '235', 'Funded by Office of Students'),
(1, 5, '240', 'Initial teacher training'),
(1, 5, '250', 'Postgraduate Teaching Apprenticeship Only'),
(1, 5, '260', 'Full Ofsted inspection'),
(1, 5, '270', 'Full Ofsted graded'),
(1, 5, '280', 'Full Ofsted grade'),
(1, 5, '290', 'Monitoring visit'),
(1, 5, '292', 'Consecutive inadequate monitoring visits'),
(1, 5, '294', 'Most recent monitoring visit'),
(1, 5, '300', 'Ofsted Apprenticeships Grade'),
(1, 5, '301', 'Ofsted Apprenticeships Grade'),
(1, 5, '310', 'Ofsted Graded within 3 years'),
(1, 5, '311', 'Ofsted Graded within 3 years'),
(1, 5, '320', 'Maintained funding since Ofsted inspection'),
(1, 5, '330', 'Short Ofsted inspection within 3 years'),
(1, 5, '340', 'Maintained short inspection grade'),
(1, 5, '350', 'Delivered apprenticeship training as subcontractor'),
(1, 5, '360', 'Subcontractor training agreement document'),
(1, 5, '10004', 'Shutter Page - Inadequate Ofsted grade within the last 3 years'),
(1, 5, '10010', 'Shutter Page - Insufficient progress made during most recent monitoring visit'),

(2, 1, '2000', 'Financial health assessment'),
(2, 1, '2010', 'Financial health assessment'),

(2, 2, '2100', 'Over £75 million for the latest reported financial year'),
(2, 2, '2110', 'ESFA funding to be less than 5% annual turnover'),
(2, 2, '2120', 'Financial evidence'),
(2, 2, '2130', 'Financial evidence'),
(2, 2, '2140', 'Financial evidence'),
(2, 2, '2150', 'Financial statements covering the last 12 months'),
(2, 2, '2160', 'Upload financial statements covering the last 12 months'),
(2, 2, '2170', 'Financial statements within the last 12 months'),
(2, 2, '2180', 'Financial statements - What you need to upload'),
(2, 2, '2190', 'Upload financial statements within the last 12 months'),
(2, 2, '2195', 'Full management accounts - What you need to upload'),
(2, 2, '2200', 'Management accounts covering the remaining period to date'),
(2, 2, '2210', 'Full management accounts covering the last 12 months'),
(2, 2, '2220', 'Management accounts - What you need to upload'),
(2, 2, '2225', 'Upload full management accounts covering the last 12 months'),
(2, 2, '2230', 'Management accounts - What you need to upload'),
(2, 2, '2240', 'Upload management accounts covering at least 3 months within the last 12 months'),
(2, 2, '2250', 'Upload financial projections covering the remaining period'),
(2, 2, '2260', 'Who prepared the answers and uploads in this section?'),
(2, 2, '2270', 'Accounting reference date'),
(2, 2, '2280', 'Accounting period months covered'),

(2, 3, '2500', 'Consolidated financial statements'),
(2, 3, '2510', 'Upload your UK ultimate parent company''s consolidated financial statements'),
(2, 3, '2520', 'Other active subsidiary companies'),
(2, 3, '2530', 'Upload a financial statement for all your UK ultimate parent company''s active subsidiary companies'),
(2, 3, '2540', 'Upload your UK ultimate parent company''s full financial statements covering the last 12 months'),

(3, 1, '3000', 'Criminal and compliance checks on your organisation'),

(3, 2, '3100', 'Composition with creditors'),
(3, 2, '3110', 'Failed to pay back funds'),
(3, 2, '3120', 'Contract terminated early by a public body'),
(3, 2, '3130', 'Withdrawn from a contract with a public body'),
(3, 2, '3135', 'Removed from the Register of Training Organisations (RoTO)'),
(3, 2, '3140', 'Funding removed from any education bodies'),
(3, 2, '3150', 'Removed from any professional or trade registers'),
(3, 2, '3160', 'Involuntarily withdrawn from Initial Teacher Training accreditation'),
(3, 2, '3170', 'Removed from any charity register'),
(3, 2, '3180', 'Investigated due to safeguarding issues'),
(3, 2, '3190', 'Subjected to an investigation by the ESFA or other public body or regulator'),
(3, 2, '3199', 'Subjected to insolvency or winding up proceedings'),

(3, 3, '3200', 'Criminal and compliance checks on who''s in control of your organisation'),

(3, 4, '3300', 'Unspent criminal convictions'),
(3, 4, '3301', 'Unspent criminal convictions'),
(3, 4, '3310', 'Failed to pay back funds'),
(3, 4, '3311', 'Failed to pay back funds'),
(3, 4, '3320', 'Investigated for fraud or irregularities'),
(3, 4, '3321', 'Investigated for fraud or irregularities'),
(3, 4, '3330', 'Ongoing investigations for fraud or irregularities'),
(3, 4, '3331', 'Ongoing investigations for fraud or irregularities'),
(3, 4, '3340', 'Contract terminated by a public body'),
(3, 4, '3341', 'Contract terminated by a public body'),
(3, 4, '3350', 'Withdrawn from a contract with a public body'),
(3, 4, '3351', 'Withdrawn from a contract with a public body'),
(3, 4, '3360', 'Breached tax payments or social security contributions'),
(3, 4, '3361', 'Breached tax payments or social security contributions'),
(3, 4, '3370', 'Register of Removed Trustees'),
(3, 4, '3371', 'Register of Removed Trustees'),
(3, 4, '3380', 'Been made bankrupt'),
(3, 4, '3381', 'Been made bankrupt'),
(3, 4, '3390', 'Been subject to a prohibition order from the Teaching Regulation Agency'),
(3, 4, '3391', 'Been subject to a prohibition order from the Teaching Regulation Agency'),
(3, 4, '3395', 'Been subject to a ban from management or governance of schools'),
(3, 4, '3396', 'Been subject to a ban from management or governance of schools'),

(4, 1, '4000', 'Protecting your apprentices'),
(4, 1, '4001', 'Protecting your apprentices'),
(4, 1, '4002', 'Protecting your apprentices'),

(4, 2, '4010', 'Continuity plan for apprenticeship training'),

(4, 3, '4020', 'Equality and diversity policy'),

(4, 4, '4030', 'Safeguarding policy'),
(4, 4, '4035', 'Overall responsibility for safeguarding'),
(4, 4, '4037', 'Safeguarding policy includes Prevent duty policy'),
(4, 4, '4038', 'Prevent duty policy'),

(4, 5, '4040', 'Health and safety policy'),
(4, 5, '4045', 'Overall responsibility for health and safety'),

(4, 6, '4050', 'Acting as a subcontractor'),

(5, 1, '5000', 'Readiness to engage'),
(5, 1, '5010', 'Readiness to engage'),
(5, 1, '5020', 'Readiness to engage'),

(5, 2, '5100', 'Engaging with employers to deliver apprenticeship training to employees'),
(5, 2, '5110', 'Managing relationships with employers'),
(5, 2, '5120', 'Overall responsibility for managing relationships with employers'),
(5, 2, '5130', 'Promote apprenticeships to employers?'),

(5, 3, '5200', 'Complaints policy'),
(5, 3, '5210', 'Website link for the complaints policy'),

(5, 4, '5300', 'Contract for services template with employers'),

(5, 5, '5400', 'Commitment statement template'),

(5, 6, '5500', 'Process for initial assessments to recognise prior learning'),
(5, 6, '5510', 'Process to assess English and maths'),

(5, 7, '5550', 'English and maths assessments'),
(5, 7, '5560', 'Locations for English and maths assessments'),
(5, 7, '5570', 'Delivering English and maths assessments if there''s a significant event'),

(5, 8, '5600', 'Using subcontractors in the first 12 months of joining the APAR'),
(5, 8, '5610', 'Due diligence on subcontractors'),

(6, 1, '6000', 'Planning apprenticeship training'),
(6, 1, '6001', 'Planning apprenticeship training'),
(6, 1, '6002', 'Planning apprenticeship training'),

(6, 2, '6201', 'Type of apprenticeship training'),
(6, 2, '6202', 'Type of apprenticeship training'),
(6, 2, '6203', 'Type of apprenticeship training'),
(6, 2, '6204', 'Type of apprenticeship training'),
(6, 2, '6205', 'Delivering training in apprenticeship standards'),
(6, 2, '6206', 'Delivering training in apprenticeship standards'),
(6, 2, '6230', 'Delivering training in apprenticeship standards'),
(6, 2, '6250', 'Transition to apprenticeship standards'),
(6, 2, '6252', 'Transitioning from apprenticeship frameworks to apprenticeship standards'),
(6, 2, '6253', 'Transitioning from apprenticeship frameworks to apprenticeship standards'),
(6, 2, '6254', 'Delivering apprenticeship frameworks only'),
(6, 2, '6260', 'Transition to apprenticeship standards'),
(6, 2, '6262', 'Transitioning from apprenticeship frameworks to apprenticeship standards'),
(6, 2, '6264', 'Delivering apprenticeship frameworks only'),
(6, 2, '6270', 'Engaging with end-point assessment organisations (EPAOs)'),
(6, 2, '6280', 'Engaging and work with awarding bodies'),

(6, 3, '6300', 'How apprentices will be trained"'),

(6, 4, '6400', 'Supporting apprentices during apprenticeship training'),
(6, 4, '6405', 'Supporting apprentices during apprenticeship training'),
(6, 4, '6410', 'Ways of supporting apprentices'),
(6, 4, '6420', 'Other ways of supporting apprentices'),

(6, 5, '6500', 'Forecasting starts in the first 12 months of joining the APAR'),
(6, 5, '6510', 'Ready to deliver training against forecast'),
(6, 5, '6520', 'Recruit new staff to deliver training against forecast'),
(6, 5, '6530', 'Typical ratio of the staff delivering training to the apprentices'),
(6, 5, '6540', 'Proposed staff to learner support'),

(6, 6, '6600', 'Methods used to deliver 20% off the job training'),
(6, 6, '6610', 'Off the job training relevant to apprenticeship being delivered'),

(6, 7, '6700', 'Where apprentices will be trained'),

(7, 1, '7000', 'Delivering apprenticeship training'),
(7, 1, '7001', 'Delivering apprenticeship training'),
(7, 1, '7002', 'Delivering apprenticeship training'),

(7, 2, '7100', 'Overall accountability for apprenticeships'),

(7, 3, '7200', 'Management hierarchy for apprenticeships'),
(7, 3, '7200-FHA', 'Turnover and full time equivalent (FTE) employees'),

(7, 4, '7300', 'Quality and high standards in apprenticeship training'),
(7, 4, '7305', 'Monitoring and evaluating expectations for quality and high standards in apprenticeship training'),
(7, 4, '7310', 'Overall responsibility for maintaining expectations for quality and high standards in apprenticeship training'),
(7, 4, '7320', 'Communicating expectations for quality and high standards in apprenticeship training to employees'),

(7, 5, '7500', 'Team responsible for developing and delivering training'),
(7, 5, '7510', 'Someone responsible for developing and delivering training'),
(7, 5, '7520', 'Someone responsible for developing and delivering training'),
(7, 5, '7530', 'Who the team have worked with to develop and deliver training'),
(7, 5, '7540', 'Overall manager for the team responsible for developing and delivering training'),
(7, 5, '7560', 'Who the person has worked with to develop and deliver training'),
(7, 5, '7570', 'How the team worked with other organisations to develop and deliver training'),
(7, 5, '7590', 'Overall manager for the team responsible for developing and delivering training'),
(7, 5, '7591', 'How the team worked with other organisations and employers to develop and deliver training'),
(7, 5, '7592', 'How the team worked with employers to develop and deliver training'),
(7, 5, '7593', 'How has this person worked with other organisations to develop and deliver training'),
(7, 5, '7594', 'How has this person worked with other organisations and employers to develop and deliver training'),
(7, 5, '7595', 'How has this person worked with employers to develop and deliver training'),

(7, 6, '7600', 'Your organisation''s sectors and employee experience'),

(7, 6, '7610AA', '''Agriculture, environmental and animal care'' - Standards offered'),
(7, 6, '7610A',  '''Agriculture, environmental and animal care'' - Number of starts'),
(7, 6, '7610B',  '''Agriculture, environmental and animal care'' - Number of employees'),
(7, 6, '7610',   '''Agriculture, environmental and animal care'' - Most experienced employee'),
(7, 6, '7611',   '''Agriculture, environmental and animal care'' - Most experienced employee''s experience'),
(7, 6, '7612',   '''Agriculture, environmental and animal care'' - Most experienced employee''s experience'),
(7, 6, '7613',   '''Agriculture, environmental and animal care'' - Most experienced employee''s experience'),

(7, 6, '7615AA', '''Business and administration'' - Standards offered'),
(7, 6, '7615A',  '''Business and administration'' - Number of starts'),
(7, 6, '7615B',  '''Business and administration'' - Number of employees'),
(7, 6, '7615',   '''Business and administration'' - Most experienced employee'),
(7, 6, '7616',   '''Business and administration'' - Most experienced employee''s experience'),
(7, 6, '7617',   '''Business and administration'' - Most experienced employee''s experience'),
(7, 6, '7618',   '''Business and administration'' - Most experienced employee''s experience'),

(7, 6, '7620AA', '''Care services'' - Standards offered'),
(7, 6, '7620A',  '''Care services'' - Number of starts'),
(7, 6, '7620B',  '''Care services'' - Number of employees'),
(7, 6, '7620',   '''Care services'' - Most experienced employee'),
(7, 6, '7621',   '''Care services'' - Most experienced employee''s experience'),
(7, 6, '7622',   '''Care services'' - Most experienced employee''s experience'),
(7, 6, '7623',   '''Care services'' - Most experienced employee''s experience'),

(7, 6, '7625AA', '''Catering and hospitality'' - Standards offered'),
(7, 6, '7625A',  '''Catering and hospitality'' - Number of starts'),
(7, 6, '7625B',  '''Catering and hospitality'' - Number of employees'),
(7, 6, '7625',   '''Catering and hospitality'' - Most experienced employee'),
(7, 6, '7626',   '''Catering and hospitality'' - Most experienced employee''s experience'),
(7, 6, '7627',   '''Catering and hospitality'' - Most experienced employee''s experience'),
(7, 6, '7628',   '''Catering and hospitality'' - Most experienced employee''s experience'),

(7, 6, '7630AA', '''Construction'' - Standards offered'),
(7, 6, '7630A',  '''Construction'' - Number of starts'),
(7, 6, '7630B',  '''Construction'' - Number of employees'),
(7, 6, '7630',   '''Construction'' - Most experienced employee'),
(7, 6, '7631',   '''Construction'' - Most experienced employee''s experience'),
(7, 6, '7632',   '''Construction'' - Most experienced employee''s experience'),
(7, 6, '7633',   '''Construction'' - Most experienced employee''s experience'),

(7, 6, '7635AA', '''Creative and design'' - Standards offered'),
(7, 6, '7635A',  '''Creative and design'' - Number of starts'),
(7, 6, '7635B',  '''Creative and design'' - Number of employees'),
(7, 6, '7635',   '''Creative and design'' - Most experienced employee'),
(7, 6, '7636',   '''Creative and design'' - Most experienced employee''s experience'),
(7, 6, '7637',   '''Creative and design'' - Most experienced employee''s experience'),
(7, 6, '7638',   '''Creative and design'' - Most experienced employee''s experience'),

(7, 6, '7640AA', '''Digital'' - Standards offered'),
(7, 6, '7640A',  '''Digital'' - Number of starts'),
(7, 6, '7640B',  '''Digital'' - Number of employees'),
(7, 6, '7640',   '''Digital'' - Most experienced employee'),
(7, 6, '7641',   '''Digital'' - Most experienced employee''s experience'),
(7, 6, '7642',   '''Digital'' - Most experienced employee''s experience'),
(7, 6, '7643',   '''Digital'' - Most experienced employee''s experience'),

(7, 6, '7645AA', '''Education and childcare'' - Standards offered'),
(7, 6, '7645A',  '''Education and childcare'' - Number of starts'),
(7, 6, '7645B',  '''Education and childcare'' - Number of employees'),
(7, 6, '7645',   '''Education and childcare'' - Most experienced employee'),
(7, 6, '7646',   '''Education and childcare'' - Most experienced employee''s experience'),
(7, 6, '7647',   '''Education and childcare'' - Most experienced employee''s experience'),
(7, 6, '7648',   '''Education and childcare'' - Most experienced employee''s experience'),

(7, 6, '7650AA', '''Engineering and manufacturing'' - Standards offered'),
(7, 6, '7650A',  '''Engineering and manufacturing'' - Number of starts'),
(7, 6, '7650B',  '''Engineering and manufacturing'' - Number of employees'),
(7, 6, '7650',   '''Engineering and manufacturing'' - Most experienced employee'),
(7, 6, '7651',   '''Engineering and manufacturing'' - Most experienced employee''s experience'),
(7, 6, '7652',   '''Engineering and manufacturing'' - Most experienced employee''s experience'),
(7, 6, '7653',   '''Engineering and manufacturing'' - Most experienced employee''s experience'),

(7, 6, '7655AA', '''Hair and Beauty'' - Standards offered'),
(7, 6, '7655A',  '''Hair and Beauty'' - Number of starts'),
(7, 6, '7655B',  '''Hair and Beauty'' - Number of employees'),
(7, 6, '7655',   '''Hair and Beauty'' - Most experienced employee'),
(7, 6, '7656',   '''Hair and Beauty'' - Most experienced employee''s experience'),
(7, 6, '7657',   '''Hair and Beauty'' - Most experienced employee''s experience'),
(7, 6, '7658',   '''Hair and Beauty'' - Most experienced employee''s experience'),

(7, 6, '7660AA', '''Health and science'' - Standards offered'),
(7, 6, '7660A',  '''Health and science'' - Number of starts'),
(7, 6, '7660B',  '''Health and science'' - Number of employees'),
(7, 6, '7660',   '''Health and science'' - Most experienced employee'),
(7, 6, '7661',   '''Health and science'' - Most experienced employee''s experience'),
(7, 6, '7662',   '''Health and science'' - Most experienced employee''s experience'),
(7, 6, '7663',   '''Health and science'' - Most experienced employee''s experience'),

(7, 6, '7665AA', '''Legal, finance and accounting'' - Standards offered'),
(7, 6, '7665A',  '''Legal, finance and accounting'' - Number of starts'),
(7, 6, '7665B',  '''Legal, finance and accounting'' - Number of employees'),
(7, 6, '7665',   '''Legal, finance and accounting'' - Most experienced employee'),
(7, 6, '7666',   '''Legal, finance and accounting'' - Most experienced employee''s experience'),
(7, 6, '7667',   '''Legal, finance and accounting'' - Most experienced employee''s experience'),
(7, 6, '7668',   '''Legal, finance and accounting'' - Most experienced employee''s experience'),

(7, 6, '7670AA', '''Protective services'' - Standards offered'),
(7, 6, '7670A',  '''Protective services'' - Number of starts'),
(7, 6, '7670B',  '''Protective services'' - Number of employees'),
(7, 6, '7670',   '''Protective services'' - Most experienced employee'),
(7, 6, '7671',   '''Protective services'' - Most experienced employee''s experience'),
(7, 6, '7672',   '''Protective services'' - Most experienced employee''s experience'),
(7, 6, '7673',   '''Protective services'' - Most experienced employee''s experience'),

(7, 6, '7675AA', '''Sales, marketing and procurement'' - Standards offered'),
(7, 6, '7675A',  '''Sales, marketing and procurement'' - Number of starts'),
(7, 6, '7675B',  '''Sales, marketing and procurement'' - Number of employees'),
(7, 6, '7675',   '''Sales, marketing and procurement'' - Most experienced employee'),
(7, 6, '7676',   '''Sales, marketing and procurement'' - Most experienced employee''s experience'),
(7, 6, '7677',   '''Sales, marketing and procurement'' - Most experienced employee''s experience'),
(7, 6, '7678',   '''Sales, marketing and procurement'' - Most experienced employee''s experience'),

(7, 6, '7680AA', '''Transport and logistics'' - Standards offered'),
(7, 6, '7680A',  '''Transport and logistics'' - Number of starts'),
(7, 6, '7680B',  '''Transport and logistics'' - Number of employees'),
(7, 6, '7680',   '''Transport and logistics'' - Most experienced employee'),
(7, 6, '7681',   '''Transport and logistics'' - Most experienced employee''s experience'),
(7, 6, '7682',   '''Transport and logistics'' - Most experienced employee''s experience'),
(7, 6, '7683',   '''Transport and logistics'' - Most experienced employee''s experience'),

(7, 7, '7700', 'Policy for professional development of employees'),
(7, 7, '7710', 'How the policy is used to improve employee sector expertise'),
(7, 7, '7720', 'How the policy is used to maintain employee teaching and training knowledge'),

(8, 1, '8000', 'Evaluating apprenticeship training'),
(8, 1, '8010', 'Evaluating apprenticeship training'),

(8, 2, '8100', 'Process for evaluating the quality of training delivered'),
(8, 2, '8110', 'Improvements made using process for evaluating the quality of training delivered'),

(8, 3, '8200', 'Process for evaluating the quality of training delivered include apprenticeship training'),
(8, 3, '8210', 'Evaluate the quality of apprenticeship training'),
(8, 3, '8220', 'Evaluate the quality of apprenticeship training'),
(8, 3, '8230', 'Review process for evaluating the quality of training delivered'),

(8, 4, '8300', 'Systems and processes to collect apprenticeship data'),
(8, 4, '8310', 'Individualised Learner Record (ILR) data'),
(8, 4, '8320', 'Who is the individual accountable for submitting ILR data for your organisation?'),

(9, 1, '9000', 'Application permissions checked'),
(9, 1, '9010', 'Application details checked'),
(9, 1, '9020', 'Permission to submit application'),
(9, 1, '10005', 'Shutter Page - Application permissions and details checks'),

(9, 2, '9100', 'Quality statement understood'),
(9, 2, '100055', 'Shutter Page - Quality statement understood'),

(9, 3, '9200', 'Post application tasks'),
(9, 3, '10006', 'Shutter Page - Post application tasks');