CREATE TABLE [review].[Gateway](
    [Id] UNIQUEIDENTIFIER NOT NULL,
    [ApplicationId] UNIQUEIDENTIFIER NOT NULL,
	[Status] NVARCHAR(20) NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL, 
    [CreatedBy] NVARCHAR(256) NOT NULL, 
    [AssignedAt] DATETIME2 NOT NULL, 
    [AssignedTo] NVARCHAR(256) NOT NULL,
	[AssignedToName] NVARCHAR(256) NOT NULL, 
    [Outcomes] NVARCHAR(MAX) NULL,
    CONSTRAINT [PK_Gateway] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [review].[Gateway]  WITH CHECK ADD  CONSTRAINT [FK_Gateway_Applications] FOREIGN KEY([ApplicationId])
REFERENCES [dbo].[Applications] ([Id])
GO

ALTER TABLE [review].[Gateway] CHECK CONSTRAINT [FK_Gateway_Applications]
GO


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Gateway] ON [review].[Gateway]
(
	[ApplicationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]